server:
  port: ${port:9000}

spring:
  application:
    name: chessbase
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/chessbase}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgrespw}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  security:
    jwt:
      secret-key: ${SECRET_KEY:}  # todo add SECRET KEY here
      expiration: 86400000 # 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days