name: Azure Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    env:
      # TIMESTAMP: ${{ github.run_id }}  # Use the GitHub run ID as a unique identifier
      TIMESTAMP: latest  # Use the GitHub run ID as a unique identifier
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Azure Container Registry
      run: |
        echo ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }} | docker login ${{ secrets.AZURE_CONTAINER_REGISTRY_LOGIN_SERVER }} -u ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }} --password-stdin
    
    - name: Build the backend Docker image
      run: docker build backend/chessBase --file backend/chessBase/Dockerfile --tag chessbase-backend:${{ env.TIMESTAMP }}
    
    - name: Tag the backend Docker image
      run: docker tag chessbase-backend:${{ env.TIMESTAMP }} ${{ secrets.AZURE_CONTAINER_REGISTRY_LOGIN_SERVER }}/chessbase-backend:${{ env.TIMESTAMP }}
    
    - name: Push the backend Docker image
      run: docker push ${{ secrets.AZURE_CONTAINER_REGISTRY_LOGIN_SERVER }}/chessbase-backend:${{ env.TIMESTAMP }}
    
    - name: Build the frontend Docker image
      run: docker build frontend --file frontend/Dockerfile --tag chessbase-frontend:${{ env.TIMESTAMP }}
    
    - name: Tag the frontend Docker image
      run: docker tag chessbase-frontend:${{ env.TIMESTAMP }} ${{ secrets.AZURE_CONTAINER_REGISTRY_LOGIN_SERVER }}/chessbase-frontend:${{ env.TIMESTAMP }}
    
    - name: Push the frontend Docker image
      run: docker push ${{ secrets.AZURE_CONTAINER_REGISTRY_LOGIN_SERVER }}/chessbase-frontend:${{ env.TIMESTAMP }}
